name: todo_list
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  animated_line_through: ^1.0.4
  bloc: ^8.1.4
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.2
  dio: ^5.4.3+1
  equatable: ^2.0.5
  firebase_analytics: ^11.2.0
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  firebase_remote_config: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  go_router: ^14.2.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  logger: ^2.3.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  rive: ^0.13.9
  shared_preferences: ^2.2.3
  shimmer_animation: ^2.2.1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/animation/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: ru
  arb_dir: lib/config/l10n/l10n
  output_dir: lib/config/l10n/generated

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image: assets/app_icon/icon.png
