name: Flutter CI

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22"
      - name: Install dependencies
        run: flutter pub get
      - name: Run flutter format and analyze
        run: dart format --set-exit-if-changed . && flutter analyze --fatal-infos --fatal-warnings || true && flutter analyze --fatal-infos --fatal-warnings | grep -v "asset_does_not_exist"
      - name: Run tests
        run: flutter test
      - name: Build APK
        run: flutter build apk --release
      - name: Build AppBundle
        run: flutter build appbundle --release
