name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22"
      - name: Create empty .env file
        run: |
          mkdir -p assets
          echo "" > assets/.env
      - name: Install dependencies
        run: flutter pub get
      - name: Run flutter format
        run: dart format --set-exit-if-changed .
      - name: Run flutter analyze
        run: flutter analyze --fatal-infos --fatal-warnings
      - name: Run tests
        run: flutter test
      - name: Build APK
        run: flutter build apk --release
      - name: Determine environment and build APK
        run: |
          if [ "$BUILD_APK" == "prod" ]; then
            flutter build apk --release -t lib/main_prod.dart
          elif [ "$BUILD_APK" == "dev" ]; then
            flutter build apk --release -t lib/main_dev.dart
          else
            echo "Error: Unknown build environment"
            exit 1
          fi
        env:
        BUILD_APK: "prod"
      - name: Determine environment and build APK
        run: |
          if [ "$BUILD_ABD" == "prod" ]; then
            flutter build appbundle --release -t lib/main_prod.dart
          elif [ "$BUILD_ABD" == "dev" ]; then
            flutter build appbundle --release -t lib/main_dev.dart
          else
            echo "Error: Unknown build environment"
            exit 1
          fi
        env:
        BUILD_ABD: "prod"
    # - name: Deploy to Firebase App Distribution
    #   env:
    #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    #   run: |
    #     firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
    #       --app <your-firebase-app-id> \
    #       --groups testers
